[project]
name = "cap-spec"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs-add-number-plugin>=1.2.2",
    "mkdocs-material>=9.6.14",
    "mkdocs-redirects>=1.2.2",
]
